easy_admin:

    entities:
        Category:
            class: App\Entity\Category
            image_base_path: 'http://static.acme.org/img/'
            default: true
            permission: ROLE_USER
            list:
                fields:
                    - { property: 'name', type: 'string' }
            edit:
            icon: 'user'
        Advert:
            class: App\Entity\Advert

        Client:
            class: App\Entity\Client
            image_base_path: '/uploads/img/'
            list:
                fields:
                    - { property: 'firstName', label: 'Prénom' }
                    - { property: 'lastName', label: 'Nom' }
                    - { property: 'user.email', label: 'Email' }
                    - { property: 'age'}
                    - { property: 'logo.filePath', label: 'Logo', type: 'image' }
            form:
                fields:
                    - { type: 'tab', label: 'Coordonné Client', icon: 'phone' }
                    - { property: 'firstName', type: 'text', label: 'Prénom' }
                    - { property: 'lastName', type: 'text', label: 'Nom' }
                    - { type: 'section', label: 'Contact User', icon: 'customer' }
                    - property: 'user'
                      type: 'App\Form\UserType'
                    - { type: 'section', label: 'Suivre Client coordonée', icon: 'customer' }
                    - { property: 'age', type: 'integer', label: 'Age' }
                    - { property: 'gender', type: 'choice', type_options: { multiple: false, choices: { 'Homme': '1', 'Femme': '2' } } }
                    - { property: 'phoneNumber', type: 'tel', label: 'Téléphone' }
                    - { property: 'logo', type: 'App\Form\MediaType' }
                    - { type: 'tab', label: 'Addresse', icon: 'customer' }
                    - property: 'address'
                      type: 'App\Form\AddressType'



        User:
            class: App\Entity\User
            form:
                fields:
                    - email
                    - { property: 'password', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            list:
                fields:
                    - { property: 'id', type: 'entier', width: 60 }
                    - { property: 'email', type: 'email', width: 50 }
                    - { property: 'roles'}
        Drug:
            class: App\Entity\Drug
            image_base_path: '/uploads/img/'
            form:
                fields:
                    - { property: 'drugName', type: 'text' }
                    - { property: 'bareCode', type: 'text' }
                    - { property: 'description', type: 'textarea' }
                    - { property: 'price', type: 'money' }
                    - { property: 'isDeleted', label: 'supprimer ?'}
                    - { property: 'expiredAt', type: 'date' }
                    - { property: 'deletedAt', type: 'date' }
                    - { property: 'pharmacy', type_options: { class: 'App\Entity\Pharmacy', choice_label: 'generatedName', multiple: 'true'} }
        Pharmacy:
            class: App\Entity\Pharmacy
            image_base_path: '/uploads/img/'
            list:
                fields:
                    - { property: 'generatedName', type: 'text' }
                    - { property: 'isActive', label: 'Active ?' }
                    - { property: 'isNight', label: 'pharmacy de nuit ?' }
                    - { property: 'isHoliday', label: 'pharmacy en vacance ?' }
                    - { property: 'logo.filePath', label: 'Logo', type: 'image'}
            new:
                item_permission: [ROLE_ADMIN, ROLE_USER]
            form:
                fields:
                    - { type: 'tab' , label: 'Basic Pharmacy Information' }
                    - { property: 'generatedName', type: 'text' }
                    - { property: 'isActive', label: 'Active ?' }
                    - { property: 'isNight', label: 'pharmacy de nuit ?' }
                    - { property: 'isHoliday', label: 'pharmacy en vacance ?' }
                    - { property: 'logo', type: 'App\Form\MediaType' }
                    - { type: 'tab', label: 'Contact User', icon: 'phone' }
                    - property: 'user'
                      type: 'App\Form\UserType'
                    - { type: 'section', label: 'Adress Details' }
                    - { property: 'address', label: 'Adresse', type: 'App\Form\AddressType' }


