easy_admin:

    entities:
        Category:
            class: App\Entity\Category
            role: ROLE_ADMIN
            image_base_path: 'http://static.acme.org/img/'
            list:
                fields:
                    - { property: 'name', type: 'string' }
        Advert:
            class: App\Entity\Advert
        Media:
            class: App\Entity\Media
            list:
                file_base_path: '/uploads/img/'
                fields:
                    - { property: 'file_path', type: 'image', filename: 'filePath_7.png'}
        User:
            class: App\Entity\User
            form:
                fields:
                    - email
                    - { property: 'password', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
            list:
                fields:
                    - { property: 'id', type: 'entier', width: 60 }
                    - { property: 'email', type: 'email', width: 50 }
                    - { property: 'roles'}

